baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = ["hugo-chart", "anatole"]
summarylength = 50

[params]
    profilePicture = "images/profile.png"
    Title = "Twitter Timelocked Investments"
    description = "An absurd speculative portfolio by Ted Slocum"
    readMore = true

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://twitter.com/TTLInvestments"

[[menu.main]]
name = "Posts"
url = "/"
weight = 1

[[menu.main]]
name = "Hypothesis"
url = "/hypothesis"
weight = 2

[[menu.main]]
name = "Performance"
url = "/performance"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 4
